name:                day04-lost-password
version:             0.1.0.0
github:              "githubuser/day04-lost-password"
license:             BSD3
author:              "Author name here"
maintainer:          "example@example.com"
copyright:           "2019 Author name here"

extra-source-files:
- README.md
- ChangeLog.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/githubuser/day04-lost-password#readme>

dependencies:
- base >= 4.7 && < 5

library:
  source-dirs: src

executables:
  day04-lost-password-exe:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    - -Wall
    - -O2
    dependencies:
    - day04-lost-password

tests:
  day04-lost-password-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    - -Wall
    - -O2
    dependencies:
    - day04-lost-password
    - hspec >= 2.7 && < 3
